# Generated by Django 3.1.5 on 2021-01-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yum.menu_item'),
        ),
    ]
