# Generated by Django 3.1.5 on 2021-01-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yum', '0002_menu_item_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yum.menu_item'),
        ),
    ]
