# Generated by Django 3.1.5 on 2021-01-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yum', '0003_auto_20210121_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu',
        ),
    ]
